### ISSUE TITLE
Different QR

### ISSUE THREAD

**Issue by PsySuck** [neos-sdi/adfsmfa#224] opened 2022-04-06 02:19 UTC
Hi. 
I updated ADFSMFA to the latest release and found weird issue:
Usage successfully registers the OTP, but the QR is different in mmc. I checked few time. QR from mmc is valid. This does not occur with all users. 
Also i can't send email - if found error in eventlog:
`Error Sending Email (KEY) for user ...: Input string was not in a correct format.`

I am using:
RSA per User.
AD as storage.

**Comment by PsySuck** [comment] 2022-04-06 02:30
I checked AD logs.
it seems TOTP is put 3 times during registration
<img width="1096" alt="Screenshot 2022-04-06 at 06 25 30" src="https://user-images.githubusercontent.com/87027160/161883983-f282a1cf-14d7-4134-9acd-a883bf5dfafe.png">
.

**Comment by redhook62** [comment] 2022-04-06 09:50
Hi, @PsySuck 

Nothing has been changed about TOTP for quite a while, it's really very weird.
When you say this happens for some users, is it always the same users or is it completely random?
For advance I would need more details.
- UPN
Are there any specifics on the upn? including length or special characters.
Can you send me (by anonymizing) the UPNs of the users concerned (replace the chars you want, imperatively keeping the length and the "-_.@" present.
- E-mail
Does the user have an email address filled in?
- TOTP Setup
can you make me a screenshot of the parameters of the TOTP config? here : [MMC TOTP Config](https://github.com/neos-sdi/adfsmfa/wiki/08A-MFA%20TOTP%20Provider#managing-mfa-otp-provider-with-mmc)
Which TOTP Applications are used (MS, Google, Ageis, ....)

You can try to unblock the situation of some users to delete their current key, before creating a new one either by the user or administratively via the console.

regards

redhook

**Comment by PsySuck** [comment] 2022-04-06 10:18
I can't find pattern. Some new users have this problem.

UPN: name@a_____.com
E-mail: it is empty after registration - i fill it via powershell.
TOTP Setup: 
<img width="819" alt="Screenshot 2022-04-06 at 13 12 24" src="https://user-images.githubusercontent.com/87027160/161953532-0868e0ac-f55f-4048-9949-e2d8f356cf67.png">

We changed 10 days ago hash algoritm from sha256 to sha1 because google authenticator. no matter what authenticator - qr code is different. It can be seen from the audio logs that the MFATOTPKey attribute changes three times.
As workaround i am using import-MFAUsersADDS.

**Comment by PsySuck** [comment] 2022-04-06 10:24
Also in eventlog a lot of these errors:
`MailSlot Client Write Error (MGT) :The system cannot find the file specified`

**Comment by PsySuck** [comment] 2022-04-06 12:29
Can i downgrade safely to previous  release?

**Comment by PsySuck** [comment] 2022-04-06 15:24
I don't understand. 
All new users cannot register. If you look at the logs, MFATOTPKEY changes three times during registration. What is the problem now: if you delete a user, he will be shown qr - then he will be able to log in and receive a message about successful registration. At the same time, there is a completely different code in the console. I will check "Solution" from https://github.com/neos-sdi/adfsmfa/issues/98

**Comment by redhook62** [comment] 2022-04-06 15:59
Hi, @PsySuck 

I'm lost myself, and don't know where you are.

Have you repositioned the hash in SHA512?
If this is the case, all users registered for more than 10 Days (before the changes you made), should connect without problems.
For users registered for 10 days (after the changes you made), the key is invalid, these users must scan a new key again or create a new key (Console/User/New Key or Console/User/Delete Key and let the user renew via the UX its key).

Then to check if there is a bug as indicate.
In the console, for a given test user. generate a new key, scan that key on the screen, then test a connection.
Then, with the same user, generate a new key and send it by email (email required), scan the QR code and test a new connection.

Tell me precisely the results, knowing that on my side all this is functional.

regards

**Comment by redhook62** [comment] 2022-04-06 21:15
Hi @PsySuck 

I for my part redid all the tests that I had asked you. I had no problem.

My configuration is: RSA / SHA512 / 6 digits / 30s
Apps Used
Microsoft Authenticator: SHA1
Google Authenticator: SHA1
Ageis Authenticator: SHA512

Each time the same QR Code scanned by the 3 applications,
For Microsoft and Google, the code is similar on the 2 applications
For Ageis, the code is different because the QR Code is in SHA512.

And of course, I managed to identify myself with each of the 3 applications, with SHA1 (MS, Google), and SHA512 (Ageis).
This is the expected behavior, and as I told you, this part hasn't changed for 4 years.
I also managed to send the emails and this in several languages

I am attaching a new build, in which I have just corrected the "Delete Key" button in the console which was not operational.

Perhaps you could update the authentication applications, and perhaps even the operating systems. also check that the time is in sync.

Thank you in advance for your return.

regards
[adfsmfa 3.1.2204.999.msi.zip](https://github.com/neos-sdi/adfsmfa/files/8430659/adfsmfa.3.1.2204.999.msi.zip)

**Comment by PsySuck** [comment] 2022-04-07 02:23
I checked Active Directory audit logs for past mouth. Sometimes during registration MFA-TOTP-Key and MFA-RSA-Certificate were update 2-3 times. Is it expected behaviour?

**Comment by PsySuck** [comment] 2022-04-07 07:43
Completely random. I found users with 1-3 modifications during registration.

**Comment by PsySuck** [comment] 2022-04-07 08:19
Yes. Currently only TOTP.

**Comment by PsySuck** [comment] 2022-04-07 09:45
Thanks, i fixed mail, wrong folder.
I received in message:
<img width="431" alt="Screenshot 2022-04-07 at 12 40 01" src="https://user-images.githubusercontent.com/87027160/162170278-2c8cc4d3-ad72-4f64-81b9-656a429762ce.png">
I decoded QR:
otpauth://totp/****-SSO:******%40****.com?secret=J7E3Z74GMGEKUBTNLRVEMWJJH7HBOKDZORF6GB6TM73JHVXNBPCNBEZLSWQYTSZCLEEI3IVGSSPX27SUCIDBSE7SR3I3SAHIMGCCNZZFLGMMAWOQ3OUKEHRNXYWCQKGFFQ7KFXJ2NFV5B4MIJ4LS2LY4WW2CQRAA5EGDR2RYQG4T4E5W4AUKGIOH5LRBDAP5UFCCK36RGBER4&issuer=****-SSO&algorithm=SHA1&digits=6&period=30

**Comment by PsySuck** [comment] 2022-04-07 12:09
Here is examples:

I delete my user. I register new OTP.
I scan my QR from mmc. Accounts name are different too
<img width="361" alt="Screenshot 2022-04-07 at 15 07 40" src="https://user-images.githubusercontent.com/87027160/162195228-7c3233f8-6784-4030-b3a2-b3dd12263d4a.png">

**Comment by redhook62** [comment] 2022-04-07 12:18
Listen, I don't know. I cannot reproduce your problem. Everything works perfectly for me on different configurations, and with customers.

**Comment by PsySuck** [comment] 2022-04-07 12:22
> Listen, I don't know. I cannot reproduce your problem. Everything works perfectly for me on different configurations, and with customers.

I understand that you can't reproduce it. maybe you can do a debug build with event logging and a key in the eventlog, or share out pdd for build 3.1.2204.999 so that I can debug it myself?

**Comment by redhook62** [comment] 2022-04-07 21:18
Hi, 

I just redid a test to check that the QRCode displayed in the UX during registration corresponds to the QRCode that will be displayed in the admin console. 

Also checked the QRCode sent by email, and finally checked the QRCode after printing. and I also redid all these tests with RSA 1024 bits.

There is therefore no worries on this side, debugging would surely be useless. version 2204.0 is not in question.

There is therefore a particularity with you, either at the level of systems, client devices (telephones and authentication applications), or MFA parameters (which for the TOTP part now seem correct).

The key you decoded is truncated, normal you chose 1024 bits. however the issuer doesn't seem correct, it's specified in 2 places normally, I don't know if your value is correct.

regards

**Comment by PsySuck** [comment] 2022-04-08 02:29
You have done an excellent job. I tested ADFSMFA for almost 8 months and had no problems. But now they are. The QR code that is shown to the user is different from what is recorded in the storage. 
There seems to be some external factor that made it more important, as only a small part of the users had the problem - now the majority, so I could not reproduce the problem before. But it is interesting that if the user was imported and he logs in in an alternative way and registers TOTP, then everything will work.
The problem is most likely unique to the environment. This is reason why i asking about pdb.

I also found that the number of users returned by `get-mfausers` changed from 1500+ to 1024 and is always like this now.

**Comment by redhook62** [comment] 2022-04-08 07:34
Hi, @PsySuck 

Okay, today i will send to you the latest build with the pdb. because I don't keep the .pdb's between each build.
The source code is available and you can do your own build anytime, @apr-un  has documented the process here: [Build](https://github.com/neos-sdi/adfsmfa/wiki/13-Build)

Tthe key that is stored is very different from the one that is used to generate the QRCode in general and is decrypted. this is normal, this key cannot be reused or copied to another user.

On the encrypted (stored) key
1) - A XOR operation with the PassPhrase of your config
2) - Using the certificate assigned to the user (pfx)
3) - Access to the private key via a password made with the checksum of the user's name
4) - Decryption operation (Asynchronous) with the private key
5) - Verification of the name of the user present somewhere in the key.
6) - key passed to the TOTP algo (time period application, hash (SHA1, SHAxxx), BASE10 conversion.
7) - Creation of the uri: authotp://totp/....

Try typing @Get-MFAUsers -IncludeDisabled to get all users

regards

**Comment by PsySuck** [comment] 2022-04-08 07:46
Thank you for explanation! 
I hope i will able to find root cause.

**Comment by redhook62** [comment] 2022-04-08 08:56
Hi,

latest sources with .pdb

[specialbuild.zip](https://github.com/neos-sdi/adfsmfa/files/8450251/specialbuild.zip)

regards

**Comment by apr-un** [comment] 2022-04-08 09:45
Hi @PsySuck 

Remember that building Your version can cause some "disturbances" in configuration, because You'll have another public key (signature) which is used to encrypt/decrypt some data from configuration. 
Safest bet is to 
export adfs configuration (backup), 
unregister Neos MFA, 
uninstall Neos MFA, 
install MFA with Your signature, 
register Yours MFA 
set all needed password/pins by MFA security cmdlet

In worst case application doesn't work because configuration problems (check logs),
in that case try to manually edit exported configuration xml and then reimport it again

@redhook62 
Today we did some more tests with my custom adapter on version 2204.0 and I can confirm that there is some kind of problem with QR code/TOTP. 
During registration of new user QR code is scanned and "works", but during logging in as this user TOTP says that its invalid code. Scanning code from MFA console application generate other code than during registration. 
I cannot debug it now, but I'll try it later


PS:
When I installed 2204.0 I also saw errors about `MailSlot Client Write Error (MGT) :The system cannot find the file specified` but after two days of 'changing' configuration changes these are gone now (don't know why). Also when I had problems with configuration I often see errors about contacting net.tcp://localhost:5987 - is this a part of MFA? 
These error are also gone now...
`Error Initializing WebAuthN Metdata Repository : There was no endpoint listening at net.tcp://localhost:5987/WebAdminService that could accept the message. This is often caused by an incorrect address or SOAP action. `

**Comment by PsySuck** [comment] 2022-04-08 09:50
@apr-un thank for you respond. I will try downgrade to older version on dev stand and find working version.

**Comment by apr-un** [comment] 2022-04-08 10:15
@PsySuck I think that downgrading is genarally ok (we did it many times), just don't go lower than version 2201 - there were changes that are written in adfs db (enums were renamed) and that caused problems with configuration deserialization :)

**Closed** 2022-04-08 17:43 UTC

**Comment by PsySuck** [comment] 2022-04-09 03:06
@redhook62 thank you!
I can confirm you fixed this.
